version: 1.0.{build}
configuration:
- Debug
- Release

#AppVeyor only use this file if you use GitHub repo.
#If you use Git public repo, you must copy this lines to your build settings

# scripts to run before build
before_build:
    - nuget restore      #install missing nuget packages

build:
  project: TypeCobol.TemplateTranspiler\TypeCobol.TemplateTranspiler.sln
  verbosity: minimal
artifacts:
- path: TypeCobol.TemplateTranspiler\bin\Release
  name: Release
notifications:
- provider: Email
  to:
  - jeanchrysostome.mayan@e-i.com
  - olivier.smedile@e-i.com
  - maxime.ball@externe.e-i.com
  subject: TypeCobol.TemplateTranspiler build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

deploy:
  provider: GitHub
  auth_token: 
    secure: oX7Ck0VMD2HvWjA2Itqc+95Azad6jIkr6C0uMLoq0gK9kKfK+UIXWvwqM6oenhkG
  artifact: Release
  draft: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only

